### PR TITLE
Add BOSH release for Varnish

### PR DESCRIPTION
**Pull request by jossy**
Checklist for submission:

- [x] LICENSE and NOTICE files are up to date
- [x] at least one final release is checked in on the default repo branch (there's a `.final_builds` folder)
- [x] of use to the general community and will be maintained
- [x] github repo must be public
- [x] bosh create-release must run successfully against all final releases (the blobstore needs to be public)
  - if not all final releases are valid, specify a `min_version`
- [x] a README explaining what the repo does
- [x] [optional] deployment manifests/ directory contains example manifest

Note: We created this bosh release quite a while ago and successfully use it in production along our Cloud Foundry deployment. However, we never came around to finalise the missing bits and pieces to share it properly.
But here we are, better late than never.

### CODE REVIEW

**Review by rkoster — APPROVED** [review]
LTGM

**Comment by rkoster** [comment]
Thanks! @jossy

**Comment by rkoster** [comment]
And its live: https://bosh.io/releases/github.com/springernature/varnish-boshrelease?all=1

**Comment by jossy** [comment]
Awesome, thank you @rkoster!

**Pull request merged**
