### PR TITLE
Update index.yml to add Ceph object storage service broker

### PR DESCRIPTION
**Pull request by bloeys**
Added a Ceph object storage service broker BOSH release

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
Hi - sorry for the delays. Is this something the general community will likely be able to use and you're able to maintain? The release and broker repositories look like there was an initial release, but not much other activity since. Also, I think it might make sense to wait on merging this until the underlying broker was something that the community could be deploying as well. I don't think there are other Ceph broker/store releases right now where BOSH users can try this out (will be great to have one).

**Comment by dpb587-pivotal** [comment]
Also, FYI, I removed the `homepage` flag [here](https://github.com/bosh-io/releases/pull/61/commits/d32004fa96a9153ad55e1c82d9f018f18d387025) since those tags imply a broader community adoption which will take some time to see for this release.

**Comment by bloeys** [comment]
Hey, no worries

Yes I do believe this will be of benefit, because as you said I don't know of other maintained and up-to-date Ceph object storage broker (if at all).

While it is true that there hasn't been much activity, this is due to it being complete so far from our POV and there are no known problems. It is maintained, was developed and is being actively used internally by the ICCLab of Zurich University of Applied Sciences.

We would generally be happy to get feedback and provide updates as time goes on, after all we use it too. If you have any concerns about it I can look into them :)

Additionally, we have support and documentation for deploying on Cloud foundry, K8S, OpenShift and of course the bosh release, so I think that covers a big chunk of users.

**Comment by bloeys** [comment]
Hello,

Its been a few months since any reply, are there any problems that need to be fixed?

**Comment by xtreme-conor-nosal** [comment]
Hi @bloeys sorry this got dropped. Is your blobstore public? Recreating final releases fails for me (e.g. `bosh create-release releases/ceph-objectstorage-broker/ceph-objectstorage-broker-1.2.1.yml`)

**Comment by mrosecrance** [comment]
Closing as we need a public blobstore to use this

**Pull request closed without merging**
