### PR TITLE
Add harbor-boshrelease into index.yml

### PR DESCRIPTION
**Pull request by jessehu**
[Project Harbor](https://github.com/vmware/harbor/) is an enterprise-class registry server 
that stores and distributes Docker images. 
Add the following snippet into the bosh deployment manifest file to deploy Project Harbor:

```
releases:
- name: harbor-container-registry
  version: 1.5.0
  sha1: ded9ed8a5e2efadc3aed26444710d8446483bd59
  url: https://storage.googleapis.com/harbor-bosh-releases/harbor-container-registry-1.5.0.tgz
```

### CODE REVIEW

**Comment by cppforlife** [comment]
@jessehu https://github.com/vmware/harbor-boshrelease/blob/master/config/final.yml does not specify s3/gcp blobstore that contains final bits hence bosh.io wont be able to pick this up.

**Comment by jessehu** [comment]
Thanks @cppforlife . I will update the final.yml and let you know.

**Comment by jessehu** [comment]
@cppforlife Is this one https://github.com/vmware/harbor-boshrelease/blob/master/releases/harbor-container-registry/harbor-container-registry-1.5.0.yml

**Comment by cppforlife** [comment]
@jessehu creating a final release generates .final_builds/ and releases/ folder updates. i dont see .final_builds though. i would recommend to rerun creation of final release (with a newer version) and commit all artifacts.

**Comment by jessehu** [comment]
Thanks @cppforlife . ".final_builds" directory is added via 'bosh create-release --final --version 1.5.0'.

**Comment by jessehu** [comment]
Hi @cppforlife, does this work ?

**Comment by cppforlife** [comment]
i ran 

```
 $ bosh cr releases/harbor-container-registry/
harbor-container-registry-1.5.0.yml  index.yml
 $ bosh cr releases/harbor-container-registry/harbor-container-registry-1.5.0.yml
-- Started downloading 'harbor-dns-aliases/26ed37cad657bcbf90c6282e09ca4be571904e35' (sha1=44f4be89e6164f1d6934fe9e64e115bfcb4c440d)
-- Started downloading 'enable-bosh-dns/733816c24ab25eb80dd82cec4ff740f90e8f5495' (sha1=a8c46ebb39e904a22fb3d125b2bbce19440b8fce)
-- Started downloading 'docker/cf939becf6700f3545d6b47849740ca3b80cf707' (sha1=ac48173ca5fb28e8324b64e6d06a9a72b5948381)
-- Started downloading 'harbor/6b0483fd21d85b07fdb902103b754fc4e365732e' (sha1=987224d4c880221a6b4e7da38028efa8a6f70f99)
-- Started downloading 'smoke-test/34742a9da2e091ce1ef3f21b24aaf823f1db4a34' (sha1=739c4e3c271f147f3837db7c98c372c301571a03)

-- Failed downloading 'smoke-test/34742a9da2e091ce1ef3f21b24aaf823f1db4a34' (sha1=739c4e3c271f147f3837db7c98c372c301571a03)


-- Failed downloading 'harbor-dns-aliases/26ed37cad657bcbf90c6282e09ca4be571904e35' (sha1=44f4be89e6164f1d6934fe9e64e115bfcb4c440d)


-- Failed downloading 'enable-bosh-dns/733816c24ab25eb80dd82cec4ff740f90e8f5495' (sha1=a8c46ebb39e904a22fb3d125b2bbce19440b8fce)


-- Failed downloading 'docker/cf939becf6700f3545d6b47849740ca3b80cf707' (sha1=ac48173ca5fb28e8324b64e6d06a9a72b5948381)


-- Failed downloading 'harbor/6b0483fd21d85b07fdb902103b754fc4e365732e' (sha1=987224d4c880221a6b4e7da38028efa8a6f70f99)


- Downloading blob '3fdccec0-e884-4184-5769-86b9cf70eaea' with digest string '739c4e3c271f147f3837db7c98c372c301571a03':
    Getting blob from inner blobstore:
      Getting blob from inner blobstore:
        googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to harbor-bosh-releases/3fdccec0-e884-4184-5769-86b9cf70eaea.</Details></Error>
- Downloading blob 'cab4d0c4-9705-4892-6bed-33acdb7d9603' with digest string '44f4be89e6164f1d6934fe9e64e115bfcb4c440d':
    Getting blob from inner blobstore:
      Getting blob from inner blobstore:
        googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to harbor-bosh-releases/cab4d0c4-9705-4892-6bed-33acdb7d9603.</Details></Error>
- Downloading blob '11d2b911-33b0-439f-52dd-3a8ed8092e54' with digest string 'a8c46ebb39e904a22fb3d125b2bbce19440b8fce':
    Getting blob from inner blobstore:
      Getting blob from inner blobstore:
        googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to harbor-bosh-releases/11d2b911-33b0-439f-52dd-3a8ed8092e54.</Details></Error>
- Downloading blob 'b5fbefd8-518c-47a0-668d-ed8b0d7aea89' with digest string 'ac48173ca5fb28e8324b64e6d06a9a72b5948381':
    Getting blob from inner blobstore:
      Getting blob from inner blobstore:
        googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to harbor-bosh-releases/b5fbefd8-518c-47a0-668d-ed8b0d7aea89.</Details></Error>
- Downloading blob '838cfacd-723d-4da1-46c3-754861a557bf' with digest string '987224d4c880221a6b4e7da38028efa8a6f70f99':
    Getting blob from inner blobstore:
      Getting blob from inner blobstore:
        googleapi: got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to harbor-bosh-releases/838cfacd-723d-4da1-46c3-754861a557bf.</Details></Error>

Exit code 1
```

sounds like you should make your bucket anon readable: https://bosh.io/docs/s3-release-blobstore/#bucket

**Comment by jessehu** [comment]
@cppforlife Sorry for late reply due to a vacation. I have made them publicly. Could you try it again please ? It works on my local box with my config/private.yml.
```
~/harbor-boshrelease$ bosh cr releases/harbor-container-registry/harbor-container-registry-1.5.0.yml
-- Started downloading 'docker/cf939becf6700f3545d6b47849740ca3b80cf707' (sha1=ac48173ca5fb28e8324b64e6d06a9a72b5948381)
... ...
9 packages

Succeeded
```

**Comment by jessehu** [comment]
Hi @cppforlife does it work now ? Thanks.

**Comment by jessehu** [comment]
Hello @cppforlife , could you please help review on this PR? Thanks very much for your time.

**Comment by jessehu** [comment]
Thanks @dpb587-pivotal a lot. This PR lives for months :)

**Comment by stonezdj** [comment]
@dpb587-pivotal  We have released harbor-container-registry v1.6.2, but https://bosh.io/release doesn't show the latest harbor-bosh releases.

**Pull request merged**
