### PR TITLE
Adds bonzofenix/vault-bbr-boshrelease

### PR DESCRIPTION
**Pull request by bonzofenix**

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
Hi! Thanks for working on this - it looks promising and I know some folks will appreciate the Vault support. A couple things...

 * The bucket does not look like it has public read enabled (`bosh create-release` will fail in a clean environment). That will need to be enabled before we can merge.
 * Do you mind if we wait on merging/publishing this until the release supports restore operations? I think users might be surprised with the partial BBR support.

**Comment by mrosecrance** [comment]
Following up on this. @bonzofenix Is this something that you still want to merge in?

**Comment by bonzofenix** [comment]
@dpb587 we worked on adding restore functionality and updated the bucket acl to be public-read on existing objects and at a bucket level for new releases.

@mrosecrance yes we still would like to get this release merged.

**Comment by belinda-liu** [comment]
Hey @bonzofenix,

Thanks for your patience. I just tried running `bosh create-release` on the repo and hit this error:

```
Blob download 'safe/safe-linux-amd64' (8.1 MB) (id: 143e7e2e-f711-4142-4ec5-b676be511f51 sha1: 4b8f8855ac21025d08bd30c23c8b0d0b9c72f88b) started
Blob download 'safe/safe-linux-amd64' (id: 143e7e2e-f711-4142-4ec5-b676be511f51) finished

Building a release from directory '/tmp/vault-bbr-boshrelease':
  - Constructing packages from directory:
      - Reading package from '/tmp/vault-bbr-boshrelease/packages/safe':
          Collecting package files:
            Unexpected error occurred: lstat /private/tmp/vault-bbr-boshrelease/src: no such file or directory
  - Constructing jobs from manifest:
      - Expected to find package 'safe' since it's a dependency of job 'vault-backup-restore'

Exit code 1
```
Could you double check that that command works on the repo? It seems like there is a file that is missing.

**Comment by bonzofenix** [comment]
Hey @belinda-liu,

we just released a new version for the project that should fix this error. 

Thanks you!

**Comment by belinda-liu** [comment]
Hey @bonzofenix,

Looks like there's another snag with running `bosh create-release` on the repo, seems like a bucket permission error? 
```
$ bosh create-release
Blob download 'safe/safe-linux-amd64' (8.1 MB) (id: 143e7e2e-f711-4142-4ec5-b676be511f51 sha1: 4b8f8855ac21025d08bd30c23c8b0d0b9c72f88b) started
Blob download 'safe/safe-linux-amd64' (id: 143e7e2e-f711-4142-4ec5-b676be511f51) finished
-- Started downloading 'safe/9b7c9440be211f509f40d700d1988208f49a7f850a60c747692aa0794cc1bc6f' (sha1=sha256:553a4ad871b4285a93bb53b8de7475f24754428e608bbf50e4cfe13b2d1193ec)
-- Started downloading 'vault-backup-restore/afe7011b022642f4139d6e74600a613c0214ed18625048c06df4491f4fc19462' (sha1=sha256:2e6566ca88afd9b8d9e913d306d8f4de3cca9836ed0f6218da42bc66f9fd9317)

-- Failed downloading 'vault-backup-restore/afe7011b022642f4139d6e74600a613c0214ed18625048c06df4491f4fc19462' (sha1=sha256:2e6566ca88afd9b8d9e913d306d8f4de3cca9836ed0f6218da42bc66f9fd9317)


-- Failed downloading 'safe/9b7c9440be211f509f40d700d1988208f49a7f850a60c747692aa0794cc1bc6f' (sha1=sha256:553a4ad871b4285a93bb53b8de7475f24754428e608bbf50e4cfe13b2d1193ec)


Building a release from directory '/tmp/vault-bbr-boshrelease':
  - Downloading blob '8af92c4c-e3d5-44ea-504b-a4c38a4d7798' with digest string 'sha256:2e6566ca88afd9b8d9e913d306d8f4de3cca9836ed0f6218da42bc66f9fd9317':
      Getting blob from inner blobstore:
        Getting blob from inner blobstore:
          AccessDenied: Access Denied
        status code: 403, request id: 2A8AADE5455ABF21, host id: NaP0mEU/FU213lbpQ3YvDPGbPHm9OqNiOrThCu892OLa/wzIJNrUFZrib1JlV0gRLSXEY17A83M=
  - Downloading blob 'a0a69ef4-e0a1-44c4-5a07-2d08b1f64b2f' with digest string 'sha256:553a4ad871b4285a93bb53b8de7475f24754428e608bbf50e4cfe13b2d1193ec':
      Getting blob from inner blobstore:
        Getting blob from inner blobstore:
          AccessDenied: Access Denied
        status code: 403, request id: A5B99D1D52C6D9E6, host id: z3FEEFQKStN6qDENgBXE3iuiWe6SFKATnzsOh8V5UDXjeXVcnUzzsUxG7G7znBPH89x4+R3LOGE=

Exit code 1
```
We need to be able to clone the repo and `bosh create-release` in a clean environment in order to merge this. Please let us know when that works and we can take a look.

Thanks!

**Comment by mrosecrance** [comment]
I'm going to close this as it's sat without a response for a while. If you fix it feel free to open a new pr.

**Pull request closed without merging**
