### PR TITLE
Added new location for docker bosh release

### PR DESCRIPTION
**Pull request by alex-slynko**

### CODE REVIEW

**Comment by alex-slynko** [comment]
@dpb587-pivotal CFCR maintains that repository. I am not sure if you still need to support old link. My understanding was that you'll check the load and eventually delete the old link when it is not accessed anymore.

**Comment by dpb587-pivotal** [comment]
What we typically do is just stop following/listing the original repository, if that's okay with you? If you know your users are tracking bosh.io for the release, you'll just want to make sure they're aware it will stop listing new versions.

**Comment by dpb587-pivotal** [comment]
I went ahead and removed the cf-platform-eng/docker-boshrelease release; they should still be accessible on bosh.io for existing consumers, but cloudfoundry-incubator/docker-boshrelease should be recommended for new consumers and versions.

Let me know if that becomes an issue for some reason and we can restore it for a grace period.

**Comment by dpb587-pivotal** [comment]
FYI, a few semi-recent versions needed to be [skipped](https://github.com/bosh-io/releases/commit/24d79f9db9e1a7e7dbd50e8c2418459a8d6b563e) due to missing golang packages. I think we discussed those package/blob issues in Slack or somewhere previously.

**Comment by alex-slynko** [comment]
Thanks @dpb587-pivotal I have fixed it

**Pull request merged**
