### PR TITLE
Add nginx-buildpack-release

### PR DESCRIPTION
**Pull request by Zanadar**
Adds new nginx buildpack release to indexed files

[#159444595]

### CODE REVIEW

**Comment by degaurab** [comment]
cc @mfine30 @dpb587-pivotal 
seems like no tracker hook to create stories.

**Comment by dpb587-pivotal** [comment]
Sorry - this repo hasn't had good maintenance processes and it requires several manual follow up steps after merge so it often gets avoided. Thanks for the reminder(s).

**Comment by heyjcollins** [comment]
From what I can tell, the nginx-buildpack-release is on bosh.io.  This shows "Merged" status, but it is this now complete?
I've got a PR in cf-deployment that's blocked on it and I believe I can proceed now but want to be sure.

Here's my cf-d PR: https://github.com/cloudfoundry/cf-deployment/pull/687

**Comment by dpb587-pivotal** [comment]
From a totally external perspective, cloudfoundry/cf-deployment#687 seems like it can be merged now.

**Comment by heyjcollins** [comment]
That's my perspective as well. I think we'll proceed.

**Pull request merged**
